# Config file for automatic testing at travis-ci.org

language: python
python: 2.7
env:
 - TOX_ENV=py27
 - TOX_ENV=style
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
services:
 - postgresql
before_script:
  - psql -c "createuser backfeed-test -SDRP" -U postgres
  - psql -c "createdb backfeed-test --owner=backfeed-test" -U postgres
