# Config file for automatic testing at travis-ci.org

language: python
python: 2.7
env:
 - TOX_ENV=py27
 - TOX_ENV=style
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
services:
 - postgresql
before_script:
  - psql -c 'create database "backfeed-test";' -U postgres
  - psql -c "create user \"backfeed-test\" with password 'backfeed'" -U postgres
  - psql -c "grant all privileges on database \"backfeed-test\" to  \"backfeed-test\"" -U postgres
